--
-- Get all person
--
SELECT DISTINCT
	PERSON_NUMB,
	BIRTH_COUNTRY,
	BIRTH_DATE,
	DF_BIRTH_DATE,
	BIRTH_LOCALITY,
	DEFAULT_ADDRESS_NO,
	PERS_START_DATE,
	DF_PERS_START_DATE,
	REC_START_DATE,
	DF_REC_START_DATE,
	REC_END_DATE,
	DF_REC_END_DATE,
	BIRTH_STATE,
	BIRTH_COUNTRY_CODE2,
	D_PERSON_NO_COUNT,
	NULLIF(P.given_name1 || ' ' , ' ' ) || NULLIF(P.given_name2 || ' ' , ' ' ) || NULLIF(P.given_name3 || ' ' , ' ' ) 
	|| COALESCE(SURNAME, '') 
	AS NAME,
	CASE WHEN ALT_P.ALT_PERSON_NUMB IS NULL THEN 0 ELSE 1 END AS IS_ALT
FROM ABR_ASIC_OWNER.ABR_ASIC_EXT_PERSON P
LEFT JOIN (
	SELECT 
	  ALT_PERSON_NUMB
	FROM ABR_ASIC_OWNER.ABR_ASIC_EXT_GEMS_ALT_P 
	where ALT_PERSON_NUMB is not null
	group by ALT_PERSON_NUMB) ALT_P ON
	P.PERSON_NUMB = ALT_P.ALT_PERSON_NUMB
WHERE
  REC_END_DATE ='0999999'

--
-- alt_p
--
SELECT 
PERSON_NUMB, 
  ALT_PERSON_NUMB,
  max(MATCH_IND) MATCH_IND
FROM ABR_ASIC_OWNER.ABR_ASIC_EXT_GEMS_ALT_P 
where ALT_PERSON_NUMB is not null
AND PERSON_NUMB<>ALT_PERSON_NUMB
group by PERSON_NUMB, ALT_PERSON_NUMB

--
-- Person and ALT_P
--
SELECT DISTINCT
	PERSON_NUMB,
	BIRTH_COUNTRY,
--	BIRTH_DATE,
	DF_BIRTH_DATE,
	BIRTH_LOCALITY,
	DEFAULT_ADDRESS_NO,
--	PERS_START_DATE,
--	DF_PERS_START_DATE,
--	REC_START_DATE,
--	DF_REC_START_DATE,
--	REC_END_DATE,
--	DF_REC_END_DATE,
	BIRTH_STATE,
--	BIRTH_COUNTRY_CODE2,
--	D_PERSON_NO_COUNT,
	NULLIF(P.given_name1 || ' ' , ' ' ) || NULLIF(P.given_name2 || ' ' , ' ' ) || NULLIF(P.given_name3 || ' ' , ' ' ) 
	|| COALESCE(SURNAME, '') 
	AS NAME,
	CASE WHEN ALT_P.ALT_PERSON_NUMB IS NULL THEN 0 ELSE 1 END AS IS_ALT
FROM ABR_ASIC_OWNER.ABR_ASIC_EXT_PERSON P
LEFT JOIN (
	SELECT 
	  ALT_PERSON_NUMB
	FROM ABR_ASIC_OWNER.ABR_ASIC_EXT_GEMS_ALT_P 
	where ALT_PERSON_NUMB is not null
	group by ALT_PERSON_NUMB) ALT_P ON
	P.PERSON_NUMB = ALT_P.ALT_PERSON_NUMB
WHERE
  REC_END_DATE ='0999999'

  
  --
  -- get alt person
  --
  SELECT 
  PERSON_NUMB, 
  ALT_PERSON_NUMB,
  CASE WHEN PERSON_NUMB=ALT_PERSON_NUMB THEN 1 ELSE 0 END AS IS_ALT
FROM ABR_ASIC_OWNER.ABR_ASIC_EXT_GEMS_ALT_P 
where ALT_PERSON_NUMB = (SELECT
  ALT_PERSON_NUMB FROM ABR_ASIC_OWNER.ABR_ASIC_EXT_GEMS_ALT_P 
  WHERE PERSON_NUMB=30380545--$PERSON_NUMB$
  )
group by PERSON_NUMB, ALT_PERSON_NUMB

--
-- get persons of all alt_person
-- 
SELECT DISTINCT
	P.PERSON_NUMB,
	BIRTH_COUNTRY,
	DF_BIRTH_DATE,
	BIRTH_LOCALITY,
	DEFAULT_ADDRESS_NO,
	BIRTH_STATE,
	NULLIF(P.given_name1 || ' ' , ' ' ) || NULLIF(P.given_name2 || ' ' , ' ' ) || NULLIF(P.given_name3 || ' ' , ' ' ) 
	|| COALESCE(SURNAME, '') 
	AS NAME,
	IS_ALT
FROM ABR_ASIC_OWNER.ABR_ASIC_EXT_PERSON P
JOIN (
  SELECT 
    PERSON_NUMB, ALT_PERSON_NUMB,
    CASE WHEN PERSON_NUMB=ALT_PERSON_NUMB THEN 1 ELSE 0 END AS IS_ALT
  FROM ABR_ASIC_OWNER.ABR_ASIC_EXT_GEMS_ALT_P 
  where ALT_PERSON_NUMB = (SELECT
    ALT_PERSON_NUMB FROM ABR_ASIC_OWNER.ABR_ASIC_EXT_GEMS_ALT_P 
    WHERE PERSON_NUMB=30380545--$PERSON_NUMB$
  )
  group by PERSON_NUMB, ALT_PERSON_NUMB
) ALT_P ON
	P.PERSON_NUMB = ALT_P.PERSON_NUMB
WHERE
  REC_END_DATE ='0999999'


  
--
-- Get ALT_P connection according to person
--
SELECT 
  PERSON_NUMB, 
  ALT_PERSON_NUMB,
  max(MATCH_IND) MATCH_IND
FROM ABR_ASIC_OWNER.ABR_ASIC_EXT_GEMS_ALT_P 
WHERE 
  ALT_PERSON_NUMB IN (
    SELECT 
      ALT_PERSON_NUMB
    FROM ABR_ASIC_OWNER.ABR_ASIC_EXT_GEMS_ALT_P 
    where ALT_PERSON_NUMB is not null
    AND PERSON_NUMB=30380545
    group by PERSON_NUMB, ALT_PERSON_NUMB)
  AND PERSON_NUMB<>ALT_PERSON_NUMB
  GROUP BY PERSON_NUMB, ALT_PERSON_NUMB
  
--
-- org and group id
--  
select * from (
SELECT 
  O.*,
  G.GROUP_ID
  FROM (
  SELECT 
    ORGANISATION_NO,
    MAX(ORG_NAME) AS ORG_NAME,
    MAX(ORG_TYPE) AS ORG_TYPE,
    MAX(ORG_STATUS) AS ORG_STATUS,
    MAX(ORG_CLASS) AS ORG_CLASS,
    MAX(ORG_SUB_CLASS) AS ORG_SUB_CLASS
  FROM ABR_ASIC_OWNER.ABR_ASIC_EXT_ORGANISATION 
  WHERE
    REGN_END_DATE =999999
    AND ORG_END_DATE =999999
--    AND ORG_NAME LIKE '%ABC%'
  GROUP BY ORGANISATION_NO
  ) O
LEFT JOIN (
  SELECT  CLIENT_ID, GROUP_ID
  FROM ABR_ASIC_EXT_GEMS_GFT 
  GROUP BY CLIENT_ID, GROUP_ID) G ON 
  O.ORGANISATION_NO=ABS(G.CLIENT_ID)
  )
where rownum<2000

--
-- get p/s group by an org
--
select * from (
  SELECT 
    ORG_NUMBER_PAR, ORG_NUMBER_SUB
  FROM ABR_ASIC_OWNER.ABR_ASIC_EXT_GEMS_PS_R 
  WHERE
    ORG_NUMBER_UPAR IN 
    (SELECT 
          ORG_NUMBER_UPAR
        FROM ABR_ASIC_OWNER.ABR_ASIC_EXT_GEMS_PS_R 
        WHERE
        ORG_NUMBER_PAR =103779148 OR ORG_NUMBER_SUB=103779148
        GROUP BY ORG_NUMBER_UPAR
      )
  GROUP BY ORG_NUMBER_PAR, ORG_NUMBER_SUB)
where ROWNUM<100
